/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BucketsRouteImport } from './routes/buckets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BucketsIndexRouteImport } from './routes/buckets.index'
import { Route as BucketsNameRouteImport } from './routes/buckets.$name'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsRoute = BucketsRouteImport.update({
  id: '/buckets',
  path: '/buckets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsIndexRoute = BucketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BucketsRoute,
} as any)
const BucketsNameRoute = BucketsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => BucketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buckets': typeof BucketsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/wallet': typeof WalletRoute
  '/buckets/$name': typeof BucketsNameRoute
  '/buckets/': typeof BucketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/wallet': typeof WalletRoute
  '/buckets/$name': typeof BucketsNameRoute
  '/buckets': typeof BucketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buckets': typeof BucketsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/wallet': typeof WalletRoute
  '/buckets/$name': typeof BucketsNameRoute
  '/buckets/': typeof BucketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buckets'
    | '/settings'
    | '/tasks'
    | '/wallet'
    | '/buckets/$name'
    | '/buckets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/tasks' | '/wallet' | '/buckets/$name' | '/buckets'
  id:
    | '__root__'
    | '/'
    | '/buckets'
    | '/settings'
    | '/tasks'
    | '/wallet'
    | '/buckets/$name'
    | '/buckets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BucketsRoute: typeof BucketsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets': {
      id: '/buckets'
      path: '/buckets'
      fullPath: '/buckets'
      preLoaderRoute: typeof BucketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/': {
      id: '/buckets/'
      path: '/'
      fullPath: '/buckets/'
      preLoaderRoute: typeof BucketsIndexRouteImport
      parentRoute: typeof BucketsRoute
    }
    '/buckets/$name': {
      id: '/buckets/$name'
      path: '/$name'
      fullPath: '/buckets/$name'
      preLoaderRoute: typeof BucketsNameRouteImport
      parentRoute: typeof BucketsRoute
    }
  }
}

interface BucketsRouteChildren {
  BucketsNameRoute: typeof BucketsNameRoute
  BucketsIndexRoute: typeof BucketsIndexRoute
}

const BucketsRouteChildren: BucketsRouteChildren = {
  BucketsNameRoute: BucketsNameRoute,
  BucketsIndexRoute: BucketsIndexRoute,
}

const BucketsRouteWithChildren =
  BucketsRoute._addFileChildren(BucketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BucketsRoute: BucketsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
