package migrations

import (
	"database/sql"
	"slices"
	"strings"
	"testing"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect"
	"github.com/uptrace/bun/dialect/pgdialect"
	"github.com/uptrace/bun/dialect/sqlitedialect"
)

func TestFrozenBaselineDDLUsesNativeIdentityAndExplicitTypes(t *testing.T) {
	models := []any{
		(*task2026090101)(nil),
		(*bucket2026090101)(nil),
		(*object2026090101)(nil),
		(*multipartPart2026090101)(nil),
		(*storageContent2026090101)(nil),
		(*storageDataSet2026090101)(nil),
		(*storageCopy2026090101)(nil),
		(*storageReplacement2026090101)(nil),
		(*storageReplacementItem2026090101)(nil),
		(*storageCleanupCopy2026090101)(nil),
		(*objectDeletion2026090101)(nil),
		(*walletOperation2026090101)(nil),
	}

	postgres := newOfflinePostgresDDLDB(t)
	for _, model := range models {
		ddl := postgres.NewCreateTable().Model(model).String()
		if !strings.Contains(strings.ToLower(ddl), `"id" bigint not null generated by default as identity`) {
			t.Errorf("PostgreSQL identity DDL missing from %s", ddl)
		}
	}
	postgresTaskDDL := postgres.NewCreateTable().Model((*task2026090101)(nil)).String()
	postgresMultipartDDL := postgres.NewCreateTable().Model((*multipartUpload2026090101)(nil)).String()
	postgresDataSetDDL := postgres.NewCreateTable().Model((*storageDataSet2026090101)(nil)).String()
	postgresObjectVersionDDL := postgres.NewCreateTable().Model((*objectVersion2026090101)(nil)).String()
	postgresReplacementDDL := postgres.NewCreateTable().Model((*storageReplacement2026090101)(nil)).String()
	postgresTaskHistoryDDL := postgres.NewCreateTable().Model((*taskHistory2026090101)(nil)).String()
	assertDDLContains(t, postgresTaskDDL, `"type" text not null`, `"input_version" integer not null`, `"retry_count" integer`)
	assertDDLNotContains(t, postgresTaskDDL, `"retry_limit"`, `"retention_until"`)
	assertDDLContains(t, postgresTaskDDL, `"input_json" jsonb not null`, `"policy_json" jsonb not null`, `"runtime_json" jsonb not null`, `"events_json" jsonb not null`)
	assertDDLContains(t, postgresTaskHistoryDDL, `"input_json" jsonb not null`, `"checkpoint_json" jsonb`)
	assertDDLNotContains(t, postgresTaskHistoryDDL, `"checkpoint_json" jsonb not null`)
	assertDDLContains(t, postgresDataSetDDL, `"generation" bigint not null default 1`, `"copy_index" integer not null`)
	assertDDLContains(t, postgresReplacementDDL, `"copy_index" integer not null`, `"seed_cursor_content_id" bigint not null default 0`)
	assertDDLContains(t, postgresObjectVersionDDL, `"metadata" jsonb not null default '{}'`)
	assertDDLContains(t, postgresMultipartDDL, `primary key ("upload_id")`)
	assertDDLNotContains(t, postgresMultipartDDL, `"id" bigint`)

	sqlite := newOfflineSQLiteDDLDB(t)
	for _, model := range models {
		ddl := sqlite.NewCreateTable().Model(model).String()
		if !strings.Contains(strings.ToLower(ddl), `"id" integer not null primary key autoincrement`) {
			t.Errorf("SQLite identity DDL missing from %s", ddl)
		}
	}
	sqliteTaskDDL := sqlite.NewCreateTable().Model((*task2026090101)(nil)).String()
	sqliteMultipartDDL := sqlite.NewCreateTable().Model((*multipartUpload2026090101)(nil)).String()
	sqliteDataSetDDL := sqlite.NewCreateTable().Model((*storageDataSet2026090101)(nil)).String()
	sqliteReplacementDDL := sqlite.NewCreateTable().Model((*storageReplacement2026090101)(nil)).String()
	assertDDLContains(t, sqliteTaskDDL, `"type" text not null`, `"input_version" integer not null`, `"retry_count" integer`)
	assertDDLNotContains(t, sqliteTaskDDL, `"retry_limit"`, `"retention_until"`)
	assertDDLContains(t, sqliteDataSetDDL, `"generation" integer not null default 1`, `"copy_index" integer not null`)
	assertDDLContains(t, sqliteReplacementDDL, `"copy_index" integer not null`, `"seed_cursor_content_id" integer not null default 0`)
	assertDDLContains(t, sqliteMultipartDDL, `primary key ("upload_id")`)
	assertDDLNotContains(t, sqliteMultipartDDL, `"id" integer`)
}

func TestSQLiteBaselineJSONUsesTextAndValidatesShape(t *testing.T) {
	db := newSQLiteMigrationDB(t, "sqlite_json_contract")
	if err := runMigrationBody(t.Context(), db, up2026090101InitialSchema); err != nil {
		t.Fatalf("create initial schema: %v", err)
	}

	for table, columns := range map[string][]string{
		"tasks":                         {"input_json", "checkpoint_json", "policy_json", "runtime_json", "events_json"},
		"task_history":                  {"input_json", "checkpoint_json", "policy_json", "runtime_json", "events_json"},
		"storage_data_sets":             {"creation_rejection"},
		"multipart_uploads":             {"metadata"},
		"object_versions":               {"metadata"},
		"provider_tier_snapshots":       {"provider_ids_json"},
		"observability_provider_states": {"reason_codes", "evidence_json"},
		"observability_data_set_states": {"reason_codes", "evidence_json"},
	} {
		applied := appliedTableColumns(t, db, table)
		for _, name := range columns {
			found := false
			for _, column := range applied {
				if column.Name == name {
					found = true
					if column.Type != "text" {
						t.Errorf("%s.%s type = %s, want text", table, name, column.Type)
					}
				}
			}
			if !found {
				t.Errorf("missing JSON column %s.%s", table, name)
			}
		}
	}

	task := insertBaselineTestTask(t, db, "json-input")
	for _, invalid := range []string{"[]", "{"} {
		mustRejectStatement(t, db, `UPDATE tasks SET input_json = ? WHERE id = ?`, invalid, task)
	}
	mustRejectStatement(t, db, `UPDATE tasks SET events_json = '{}' WHERE id = ?`, task)
}

func TestAppliedBaselineColumnContracts(t *testing.T) {
	// A DEFAULT current_timestamp column is written by the database whenever bun
	// omits it, and SQLite renders that as second-granularity local text while
	// bun renders a fractional offset timestamp. One column would then hold two
	// encodings whose lexical order disagrees with time inside the same second.
	testMigrationDialects(t, func(t *testing.T, db *bun.DB) {
		if err := runMigrationBody(t.Context(), db, up2026090101InitialSchema); err != nil {
			t.Fatalf("create initial schema: %v", err)
		}
		for _, table := range applicationSchemaTables(t, db) {
			for _, column := range appliedTableColumns(t, db, table) {
				if strings.Contains(strings.ToLower(column.Default), "current_timestamp") {
					t.Errorf("%s.%s still defaults to the database clock: %s", table, column.Name, column.Default)
				}
			}
		}
		if db.Dialect().Name() == dialect.PG {
			var collations []string
			if err := db.NewRaw(`SELECT c.relname || '.' || a.attname || '=' || co.collname
				FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_collation co ON co.oid = a.attcollation
				WHERE c.relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = current_schema())
				AND ((c.relname = 'buckets' AND a.attname = 'name') OR (c.relname IN ('objects','object_versions','multipart_uploads','object_deletions') AND a.attname = 'key'))
				ORDER BY c.relname`).Scan(t.Context(), &collations); err != nil {
				t.Fatal(err)
			}
			if len(collations) != 5 {
				t.Fatalf("missing key columns: %v", collations)
			}
			for _, value := range collations {
				if !strings.HasSuffix(value, "=C") {
					t.Errorf("key collation %s, want C", value)
				}
			}
		}
	})
}

func TestBaselineHistoryIndexesRetainQueryPredicates(t *testing.T) {
	testMigrationDialects(t, func(t *testing.T, db *bun.DB) {
		if err := runMigrationBody(t.Context(), db, up2026090101InitialSchema); err != nil {
			t.Fatal(err)
		}
		lines, err := indexLines(t.Context(), db, []string{"task_history"}, false)
		if err != nil {
			t.Fatal(err)
		}
		columns := []string{"subject_type", "subject_key", "status", "superseded_at", "task_id"}
		predicate := ""
		if db.Dialect().Name() == dialect.PG {
			columns = []string{"subject_type", "subject_key", "superseded_at", "task_id"}
			predicate = "status = 'failed' AND superseded_at IS NULL"
		}
		for _, want := range []string{
			indexLine("task_history", "idx_task_history_status_id", false, []string{"status", "task_id"}, "", true),
			indexLine("task_history", "idx_task_history_current_failed_subject", false, columns, predicate, true),
		} {
			if !slices.Contains(lines, want) {
				t.Errorf("missing history query index %s in %v", want, lines)
			}
		}
	})
}

func newOfflinePostgresDDLDB(t *testing.T) *bun.DB {
	t.Helper()
	sqldb, err := sql.Open("pgx", "postgres://invalid")
	if err != nil {
		t.Fatalf("open offline PostgreSQL dialect: %v", err)
	}
	db := bun.NewDB(sqldb, pgdialect.New())
	t.Cleanup(func() { _ = db.Close() })
	return db
}

func newOfflineSQLiteDDLDB(t *testing.T) *bun.DB {
	t.Helper()
	sqldb, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatalf("open offline SQLite dialect: %v", err)
	}
	db := bun.NewDB(sqldb, sqlitedialect.New())
	t.Cleanup(func() { _ = db.Close() })
	return db
}

func assertDDLContains(t *testing.T, ddl string, fragments ...string) {
	t.Helper()
	ddl = strings.ToLower(ddl)
	for _, fragment := range fragments {
		fragment = strings.ToLower(fragment)
		if !strings.Contains(ddl, fragment) {
			t.Errorf("DDL %q does not contain %q", ddl, fragment)
		}
	}
}

func assertDDLNotContains(t *testing.T, ddl string, fragments ...string) {
	t.Helper()
	ddl = strings.ToLower(ddl)
	for _, fragment := range fragments {
		fragment = strings.ToLower(fragment)
		if strings.Contains(ddl, fragment) {
			t.Errorf("DDL %q unexpectedly contains %q", ddl, fragment)
		}
	}
}
