package migrations

import (
	"database/sql"
	"strings"
	"testing"

	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"
	"github.com/uptrace/bun/dialect/sqlitedialect"
)

func TestFrozenBaselineDDLUsesNativeIdentityAndExplicitTypes(t *testing.T) {
	models := []any{
		(*task2026090101)(nil),
		(*bucket2026090101)(nil),
		(*object2026090101)(nil),
		(*multipartPart2026090101)(nil),
		(*storageContent2026090101)(nil),
		(*storageDataSet2026090101)(nil),
		(*storageCopy2026090101)(nil),
		(*storageReplacement2026090101)(nil),
		(*storageReplacementItem2026090101)(nil),
		(*storageCleanupCopy2026090101)(nil),
		(*objectDeletion2026090101)(nil),
		(*walletOperation2026090101)(nil),
	}

	postgres := newOfflinePostgresDDLDB(t)
	for _, model := range models {
		ddl := postgres.NewCreateTable().Model(model).String()
		if !strings.Contains(strings.ToLower(ddl), `"id" bigint not null generated by default as identity`) {
			t.Errorf("PostgreSQL identity DDL missing from %s", ddl)
		}
	}
	postgresTaskDDL := postgres.NewCreateTable().Model((*task2026090101)(nil)).String()
	postgresMultipartDDL := postgres.NewCreateTable().Model((*multipartUpload2026090101)(nil)).String()
	postgresDataSetDDL := postgres.NewCreateTable().Model((*storageDataSet2026090101)(nil)).String()
	postgresObjectVersionDDL := postgres.NewCreateTable().Model((*objectVersion2026090101)(nil)).String()
	postgresReplacementDDL := postgres.NewCreateTable().Model((*storageReplacement2026090101)(nil)).String()
	postgresTaskPayloadDDL := postgres.NewCreateTable().Model((*taskPayload2026090101)(nil)).String()
	assertDDLContains(t, postgresTaskDDL, `"type" text not null`, `"input_version" integer not null`, `"retry_limit" integer`)
	assertDDLNotContains(t, postgresTaskDDL, `"input_json"`, `"checkpoint_json"`, `"retry_limit" integer not null`)
	assertDDLContains(t, postgresTaskPayloadDDL, `"input_json" jsonb not null`, `"checkpoint_json" jsonb`)
	assertDDLNotContains(t, postgresTaskPayloadDDL, `"checkpoint_json" jsonb not null`)
	assertDDLContains(t, postgresDataSetDDL, `"generation" bigint not null default 1`, `"copy_index" integer not null`)
	assertDDLContains(t, postgresReplacementDDL, `"items_total" integer not null default 0`, `"items_copied" integer not null default 0`)
	assertDDLContains(t, postgresObjectVersionDDL, `"metadata" jsonb not null default '{}'`)
	assertDDLContains(t, postgresMultipartDDL, `primary key ("upload_id")`)
	assertDDLNotContains(t, postgresMultipartDDL, `"id" bigint`)

	sqlite := newOfflineSQLiteDDLDB(t)
	for _, model := range models {
		ddl := sqlite.NewCreateTable().Model(model).String()
		if !strings.Contains(strings.ToLower(ddl), `"id" integer not null primary key autoincrement`) {
			t.Errorf("SQLite identity DDL missing from %s", ddl)
		}
	}
	sqliteTaskDDL := sqlite.NewCreateTable().Model((*task2026090101)(nil)).String()
	sqliteMultipartDDL := sqlite.NewCreateTable().Model((*multipartUpload2026090101)(nil)).String()
	sqliteDataSetDDL := sqlite.NewCreateTable().Model((*storageDataSet2026090101)(nil)).String()
	sqliteReplacementDDL := sqlite.NewCreateTable().Model((*storageReplacement2026090101)(nil)).String()
	assertDDLContains(t, sqliteTaskDDL, `"type" text not null`, `"input_version" integer not null`, `"retry_limit" integer`)
	assertDDLNotContains(t, sqliteTaskDDL, `"retry_limit" integer not null`)
	assertDDLContains(t, sqliteDataSetDDL, `"generation" integer not null default 1`, `"copy_index" integer not null`)
	assertDDLContains(t, sqliteReplacementDDL, `"items_total" integer not null default 0`, `"items_copied" integer not null default 0`)
	assertDDLContains(t, sqliteMultipartDDL, `primary key ("upload_id")`)
	assertDDLNotContains(t, sqliteMultipartDDL, `"id" integer`)
}

func TestSQLiteBaselineJSONUsesTextAndValidatesShape(t *testing.T) {
	db := newSQLiteMigrationDB(t, "sqlite_json_contract")
	if err := runMigrationBody(t.Context(), db, up2026090101InitialSchema); err != nil {
		t.Fatalf("create initial schema: %v", err)
	}

	for table, columns := range map[string][]string{
		"task_payloads":                 {"input_json", "checkpoint_json"},
		"multipart_uploads":             {"metadata"},
		"object_versions":               {"metadata"},
		"observability_provider_states": {"reason_codes", "evidence_json"},
		"observability_data_set_states": {"reason_codes", "evidence_json"},
	} {
		applied := appliedSQLiteColumns(t, db, table)
		for _, name := range columns {
			found := false
			for _, column := range applied {
				if column.Name == name {
					found = true
					if column.Type != "text" {
						t.Errorf("%s.%s type = %s, want text", table, name, column.Type)
					}
				}
			}
			if !found {
				t.Errorf("missing JSON column %s.%s", table, name)
			}
		}
	}

	if _, err := db.Exec(`INSERT INTO tasks
		(id, type, idempotency_key, input_version, input_hash, available_at, created_at, updated_at)
		VALUES (1, 'json-test', 'valid', 1, 'hash', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)`); err != nil {
		t.Fatalf("insert task: %v", err)
	}
	if _, err := db.Exec(`INSERT INTO task_payloads (task_id, input_json) VALUES (1, '{}')`); err != nil {
		t.Fatalf("insert valid object JSON: %v", err)
	}
	if _, err := db.Exec(`INSERT INTO task_payloads (task_id, input_json) VALUES (1, '[]')`); err == nil {
		t.Fatal("object-shaped task input accepted an array")
	}
	if _, err := db.Exec(`INSERT INTO task_payloads (task_id, input_json) VALUES (1, '{')`); err == nil {
		t.Fatal("task input accepted invalid JSON")
	}
}

func TestAppliedBaselineCarriesNoTimestampDefaults(t *testing.T) {
	// A DEFAULT current_timestamp column is written by the database whenever bun
	// omits it, and SQLite renders that as second-granularity local text while
	// bun renders a fractional offset timestamp. One column would then hold two
	// encodings whose lexical order disagrees with time inside the same second.
	testMigrationDialects(t, func(t *testing.T, db *bun.DB) {
		if err := runMigrationBody(t.Context(), db, up2026090101InitialSchema); err != nil {
			t.Fatalf("create initial schema: %v", err)
		}
		for _, table := range applicationSchemaTables(t, db) {
			for _, column := range appliedTableColumns(t, db, table) {
				if strings.Contains(strings.ToLower(column.Default), "current_timestamp") {
					t.Errorf("%s.%s still defaults to the database clock: %s", table, column.Name, column.Default)
				}
			}
		}
	})
}

func TestFrozenBaselineIndexDDLRetainsPredicates(t *testing.T) {
	for name, db := range map[string]*bun.DB{
		"Postgres": newOfflinePostgresDDLDB(t),
		"SQLite":   newOfflineSQLiteDDLDB(t),
	} {
		t.Run(name, func(t *testing.T) {
			query := db.NewCreateIndex().
				Index("idx_tasks_pending").
				Table("tasks").
				ColumnExpr("available_at").
				ColumnExpr("id").
				Where("status = 'pending'")
			buf, err := query.AppendQuery(db.QueryGen(), nil)
			if err != nil {
				t.Fatalf("render index DDL: %v", err)
			}
			ddl := string(buf)
			assertDDLContains(t, ddl, `"idx_tasks_pending"`, `available_at, id`, `where (status = 'pending')`)
		})
	}
}

func newOfflinePostgresDDLDB(t *testing.T) *bun.DB {
	t.Helper()
	sqldb, err := sql.Open("pgx", "postgres://invalid")
	if err != nil {
		t.Fatalf("open offline PostgreSQL dialect: %v", err)
	}
	db := bun.NewDB(sqldb, pgdialect.New())
	t.Cleanup(func() { _ = db.Close() })
	return db
}

func newOfflineSQLiteDDLDB(t *testing.T) *bun.DB {
	t.Helper()
	sqldb, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatalf("open offline SQLite dialect: %v", err)
	}
	db := bun.NewDB(sqldb, sqlitedialect.New())
	t.Cleanup(func() { _ = db.Close() })
	return db
}

func assertDDLContains(t *testing.T, ddl string, fragments ...string) {
	t.Helper()
	ddl = strings.ToLower(ddl)
	for _, fragment := range fragments {
		fragment = strings.ToLower(fragment)
		if !strings.Contains(ddl, fragment) {
			t.Errorf("DDL %q does not contain %q", ddl, fragment)
		}
	}
}

func assertDDLNotContains(t *testing.T, ddl string, fragments ...string) {
	t.Helper()
	ddl = strings.ToLower(ddl)
	for _, fragment := range fragments {
		fragment = strings.ToLower(fragment)
		if strings.Contains(ddl, fragment) {
			t.Errorf("DDL %q unexpectedly contains %q", ddl, fragment)
		}
	}
}
